"""Renders synthetic documents as PDFs so agents (and people) can open a real file.

Values come from the same database the APIs use, so the PDF, the API and the UI always agree.
Every page is watermarked SYNTHETIC DEMO DATA.
"""
import io
import os

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas

from . import config
from .db import q_all, q_one

GREEN = colors.HexColor("#00733C")
GOLD = colors.HexColor("#F2B705")


def _peso(v):
    return f"PHP {float(v or 0):,.2f}"


def _header(c, title, customer, page, total):
    w, h = A4
    c.setFillColor(GREEN)
    c.rect(0, h - 28 * mm, w, 28 * mm, fill=1, stroke=0)
    c.setFillColor(GOLD)
    c.rect(0, h - 29.5 * mm, w, 1.5 * mm, fill=1, stroke=0)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 15)
    c.drawString(15 * mm, h - 13 * mm, "LANDBANK MSME Lending - Demo Document")
    c.setFont("Helvetica", 10)
    c.drawString(15 * mm, h - 20 * mm, title)
    c.setFillColor(colors.black)
    c.setFont("Helvetica", 9)
    c.drawString(15 * mm, h - 37 * mm, f"{customer['business_name']}  |  {customer['customer_id']}  |  TIN {customer['tin']}")
    c.drawString(15 * mm, h - 42 * mm, f"{customer['address']}")
    c.setFont("Helvetica", 8)
    c.setFillColor(colors.grey)
    c.drawRightString(w - 15 * mm, 10 * mm, f"Page {page} of {total}")
    c.drawString(15 * mm, 10 * mm, "SYNTHETIC DEMO DATA - not a real document. Generated by the LANDBANK demo data service.")
    c.saveState()
    c.setFont("Helvetica-Bold", 48)
    c.setFillColor(colors.Color(0, 0.45, 0.24, alpha=0.07))
    c.translate(w / 2, h / 2)
    c.rotate(35)
    c.drawCentredString(0, 0, "SYNTHETIC DATA")
    c.restoreState()
    c.setFillColor(colors.black)


def _rows(c, rows, y, col_x):
    for r in rows:
        if y < 25 * mm:
            break
        for x, val in zip(col_x, r):
            c.drawString(x, y, str(val))
        y -= 6 * mm
    return y


def render_document_pdf(conn, doc):
    if doc.get("source") == "UPLOAD" and doc.get("file_name"):
        path = os.path.join(config.UPLOAD_DIR, doc["file_name"])
        if os.path.exists(path):
            with open(path, "rb") as fh:
                return fh.read()
    from .services.applications import document_extract
    cust = q_one(conn, "SELECT * FROM customers WHERE customer_id=%(c)s", {"c": doc["customer_id"]})
    dname = q_one(conn, "SELECT name FROM document_types WHERE doc_type=%(d)s", {"d": doc["doc_type"]})["name"]
    x = document_extract(conn, doc) or {}
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    col = [15 * mm, 70 * mm, 120 * mm, 160 * mm]
    dt = doc["doc_type"]
    if dt == "AUDITED_FS":
        total = doc.get("pages_expected") or 8
        n = doc.get("pages_received") or total
        titles = ["Independent auditor's report", "Statement of financial position", "Statement of comprehensive income",
                  "Statement of changes in equity", "Statement of cash flows", "Notes 1-4", "Notes 5-9", "Notes 10-14"]
        for p in range(1, n + 1):
            _header(c, f"{dname} - FY2025", cust, p, total)
            c.setFont("Helvetica-Bold", 12)
            c.drawString(15 * mm, 250 * mm, titles[p - 1])
            c.setFont("Helvetica", 10)
            if p in (2, 3):
                _rows(c, [("Revenue", _peso(x.get("revenue"))), ("Net income", _peso(x.get("net_income"))),
                          ("Total assets", _peso(x.get("total_assets"))), ("Total liabilities", _peso(x.get("total_liabilities")))],
                      238 * mm, col)
            else:
                c.drawString(15 * mm, 238 * mm, "(Synthetic narrative content)")
            c.showPage()
    else:
        _header(c, dname, cust, 1, 1)
        c.setFont("Helvetica", 10)
        y = 250 * mm
        if dt == "BANK_STATEMENTS_12M":
            y = _rows(c, [("Period", f"{x.get('period_start')} to {x.get('period_end')}"), ("Transactions", x.get("transactions")),
                          ("Total credits", _peso(x.get("total_credits"))), ("Total debits", _peso(x.get("total_debits"))),
                          ("Customer receipts", _peso(x.get("customer_receipts")))], y, col)
            y -= 4 * mm
            c.setFont("Helvetica-Bold", 9)
            y = _rows(c, [("Month", "Inflow", "Outflow", "Closing balance")], y, col)
            c.setFont("Helvetica", 9)
            months = q_all(conn, """SELECT to_char(date_trunc('month', txn_date),'YYYY-MM') AS m,
                                           SUM(amount) FILTER (WHERE direction='CREDIT') AS i, SUM(amount) FILTER (WHERE direction='DEBIT') AS o,
                                           (ARRAY_AGG(balance_after ORDER BY txn_date DESC, txn_id DESC))[1] AS b
                                    FROM transactions WHERE customer_id=%(c)s GROUP BY 1 ORDER BY 1""", {"c": doc["customer_id"]})
            _rows(c, [(m["m"], _peso(m["i"]), _peso(m["o"]), _peso(m["b"])) for m in months], y, col)
        elif dt == "VAT_RETURNS":
            c.setFont("Helvetica-Bold", 9)
            y = _rows(c, [("Form / period", "Declared gross sales", "Tax due", "Status / filed")], y, col)
            c.setFont("Helvetica", 9)
            _rows(c, [(f"{f['form_code']} {f['period_label']}", _peso(f["declared_gross_sales"]), _peso(f["tax_due"]),
                       f"{f['status']} {f['filed_on']}") for f in x.get("filings", [])], y, col)
        else:
            _rows(c, [(k.replace("_", " ").capitalize(), _peso(v) if isinstance(v, float) else v) for k, v in x.items()], y, col)
        c.showPage()
    c.save()
    return buf.getvalue()
